version: '3.7'

services:

  react:
    container_name: todos
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
